# ------------------------ Imports ------------------------
# Interface imports
from game_interface.move_interface import move as move_int


# ------------------------ Interface ------------------------
class board:
    def __init__(self):
        pass

    def __repr__(self) -> str: ...

    def minimum_players(self) -> int: ...

    def maximum_players(self) -> int: ...

    def board_deepcopy(self): ...

    def make_move(self, move: move_int): ...

    def possible_moves(self, player: str) -> list[move_int]: ...

    def get_winner(self) -> int: ...

    def maximum_tries(self) -> int: ...
